[package]
name = "schnorrprime"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
curve25519-dalek = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["cuda"]
cuda = []